import { jsPDF } from "jspdf";
import { DocumentData } from "../types";

export function generateAcademicPDF(data: DocumentData, typeId: string) {
  // A4 dimensions in pt: 595.28 x 841.89
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 54; // 0.75 in (~54pt) standard margins

  // Convert hex color to rgb array
  const hex = data.themeColor || "#7c3aed";
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);

  let currentY = margin;

  // Draw lines helper
  function drawLine(x1: number, y1: number, x2: number, y2: number, width = 1, rgb: [number, number, number] = [0, 0, 0]) {
    doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
    doc.setLineWidth(width);
    doc.line(x1, y1, x2, y2);
  }

  // Helper: Draw standard page outline/borders
  function drawBordersAndGuides(activePageNum: number) {
    if (data.showBorder) {
      doc.setDrawColor(r, g, b);
      doc.setLineWidth(1.5);
      
      if (data.accentStyle === "classic") {
        // Double border
        doc.rect(margin - 10, margin - 10, pageWidth - 2 * (margin - 10), pageHeight - 2 * (margin - 10));
        doc.setLineWidth(0.5);
        doc.rect(margin - 6, margin - 6, pageWidth - 2 * (margin - 6), pageHeight - 2 * (margin - 6));
      } else if (data.accentStyle === "modern-border") {
        // Left thick accent bar
        doc.rect(margin - 10, margin - 10, pageWidth - 2 * (margin - 10), pageHeight - 2 * (margin - 10));
        doc.setFillColor(r, g, b);
        doc.rect(margin - 10, margin - 10, 8, pageHeight - 2 * (margin - 10), "F");
      } else if (data.accentStyle === "geometric-badge") {
        doc.rect(margin - 10, margin - 10, pageWidth - 2 * (margin - 10), pageHeight - 2 * (margin - 10));
        doc.setFillColor(r, g, b);
        const sz = 6;
        doc.rect(margin - 10, margin - 10, sz, sz, "F");
        doc.rect(pageWidth - margin + 4, margin - 10, sz, sz, "F");
        doc.rect(margin - 10, pageHeight - margin + 4, sz, sz, "F");
        doc.rect(pageWidth - margin + 4, pageHeight - margin + 4, sz, sz, "F");
      } else {
        // Minimalist border
        doc.setLineWidth(0.75);
        doc.rect(margin - 10, margin - 10, pageWidth - 2 * (margin - 10), pageHeight - 2 * (margin - 10));
      }
    }

    if (data.showWatermark) {
      doc.setTextColor(240, 240, 240);
      doc.setFont("times", "italic");
      doc.setFontSize(28);
      // Angle supported directly in options parameter of text() call
      doc.text(
        data.universityName || "UNIVERSITY DOCUMENT BASE", 
        pageWidth / 2, 
        pageHeight / 2, 
        { align: "center", angle: 45 }
      );
    }

    // Header on subsequent pages
    if (activePageNum > 1) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      drawLine(margin, margin - 15, pageWidth - margin, margin - 15, 0.5, [180, 180, 180]);
      doc.text(data.universityName ? data.universityName.toUpperCase() : "ACADEMIC TRANSCRIPT", margin, margin - 22);
      doc.text(data.documentTitle || "", pageWidth - margin, margin - 22, { align: "right" });
    }

    // Footers
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`Page ${activePageNum}`, pageWidth - margin, pageHeight - 20, { align: "right" });
    doc.text("Generated by University Document Generator (UniDoc)", margin, pageHeight - 20);
  }

  // --- DRAW PAGE 1 (COVER INFO LAYOUT) ---
  drawBordersAndGuides(1);

  const primaryFont = data.fontFamily === "serif" ? "times" : data.fontFamily === "mono" ? "courier" : "helvetica";
  const boldStyle = "bold";
  const italicStyle = "italic";
  const normalStyle = "normal";

  // Spacer
  currentY += 40;

  // 1. University Title Name
  if (data.universityName) {
    doc.setFont(primaryFont, boldStyle);
    doc.setFontSize(18);
    doc.setTextColor(r, g, b);
    const univText = data.universityName.toUpperCase();
    const wrappedUniv = doc.splitTextToSize(univText, pageWidth - 2 * margin);
    wrappedUniv.forEach((line: string) => {
      doc.text(line, pageWidth / 2, currentY, { align: "center" });
      currentY += 22;
    });
  }

  // 2. Department Name
  if (data.department) {
    doc.setFont(primaryFont, italicStyle);
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    const wrappedDept = doc.splitTextToSize(data.department, pageWidth - 2 * margin);
    wrappedDept.forEach((line: string) => {
      doc.text(line, pageWidth / 2, currentY, { align: "center" });
      currentY += 16;
    });
  }

  currentY += 15;
  drawLine(pageWidth / 4, currentY, (3 * pageWidth) / 4, currentY, 1.5, [r, g, b]);
  currentY += 40;

  // 3. Central Academy Seal
  doc.setDrawColor(r, g, b);
  doc.setLineWidth(1);
  const circleX = pageWidth / 2;
  const circleY = currentY + 30;
  const circleRadius = 35 * (data.scaleLogo || 1.0);
  doc.circle(circleX, circleY, circleRadius);
  doc.circle(circleX, circleY, circleRadius - 4);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(r, g, b);
  doc.text("★", circleX - 16, circleY + 3);
  doc.text("★", circleX + 11, circleY + 3);
  
  doc.setFontSize(6);
  doc.text("VERITAS", circleX, circleY - 10, { align: "center" });
  doc.text("1902", circleX, circleY + 16, { align: "center" });
  
  // Seal interior elements
  doc.setLineWidth(1.5);
  doc.line(circleX - 8, circleY + 4, circleX + 8, circleY + 4);
  doc.line(circleX - 5, circleY, circleX + 5, circleY);
  doc.line(circleX, circleY - 4, circleX, circleY + 4);

  currentY += circleRadius * 2 + 50;

  // 4. Main Document Title
  doc.setFont(primaryFont, boldStyle);
  doc.setFontSize(22);
  doc.setTextColor(30, 30, 30);
  const wrappedTitle = doc.splitTextToSize(data.documentTitle || "Title of Academic Document", pageWidth - 2 * margin - 20);
  wrappedTitle.forEach((line: string) => {
    doc.text(line, pageWidth / 2, currentY, { align: "center" });
    currentY += 26;
  });

  // 5. Subtitle
  if (data.subtitle) {
    currentY += 6;
    doc.setFont(primaryFont, normalStyle);
    doc.setFontSize(11);
    doc.setTextColor(90, 90, 90);
    const wrappedSub = doc.splitTextToSize(data.subtitle, pageWidth - 2 * margin - 30);
    wrappedSub.forEach((line: string) => {
      doc.text(line, pageWidth / 2, currentY, { align: "center" });
      currentY += 17;
    });
  }

  // 6. Course Title
  if (data.courseName || data.courseCode) {
    currentY += 35;
    doc.setFont(primaryFont, boldStyle);
    doc.setFontSize(13);
    doc.setTextColor(50, 50, 50);
    const courseStr = [data.courseCode, data.courseName].filter(Boolean).join(" - ");
    doc.text(courseStr, pageWidth / 2, currentY, { align: "center" });
  }

  // Push the submission details to bottom A4 panel
  currentY = Math.max(currentY + 50, pageHeight - margin - 230);

  // Grey Metadata Solid Background Grid
  doc.setFillColor(248, 249, 250);
  doc.rect(margin + 10, currentY - 15, pageWidth - 2 * margin - 20, 130, "F");
  
  doc.setDrawColor(220, 224, 230);
  doc.setLineWidth(0.5);
  doc.rect(margin + 10, currentY - 15, pageWidth - 2 * margin - 20, 130);

  // Set Metadata columns
  let metaY = currentY + 10;
  
  // Column 1: Student
  doc.setFont(primaryFont, boldStyle);
  doc.setFontSize(10);
  doc.setTextColor(r, g, b);
  doc.text("STUDENT DETAILS", margin + 30, metaY);
  metaY += 18;

  doc.setFont(primaryFont, normalStyle);
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  
  if (data.studentName) {
    doc.setFont(primaryFont, boldStyle);
    doc.text(`Name:`, margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.studentName, margin + 80, metaY);
    metaY += 15;
  }
  
  if (data.studentId) {
    doc.setFont(primaryFont, boldStyle);
    doc.text(`ID/Roll:`, margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.studentId, margin + 80, metaY);
    metaY += 15;
  }

  // Handle partners / team members listing on Cover
  if (typeId === "project-report" && data.groupMembers) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Team:", margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.setFontSize(8.5);
    const teamLines = data.groupMembers.split("\n");
    let teamOffset = 0;
    teamLines.slice(0, 3).forEach((line) => {
      doc.text(line, margin + 80, metaY + teamOffset);
      teamOffset += 11;
    });
    doc.setFontSize(10);
  } else if (typeId === "presentation-cover" && data.presenters) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Team:", margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.setFontSize(8.5);
    const presenterLines = data.presenters.split("\n");
    let presOffset = 0;
    presenterLines.slice(0, 3).forEach((line) => {
      doc.text(line, margin + 80, metaY + presOffset);
      presOffset += 11;
    });
    doc.setFontSize(10);
  } else if (typeId === "internship-report" && data.internshipDuration) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Duration:", margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.internshipDuration, margin + 80, metaY);
  } else {
    doc.setFont(primaryFont, boldStyle);
    doc.text(`Course:`, margin + 30, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.courseCode || "Semester Requirement", margin + 80, metaY);
  }

  // Column 2: Evaluator / Stamp
  metaY = currentY + 10;
  const rightColX = pageWidth / 2 + 20;

  doc.setFont(primaryFont, boldStyle);
  doc.setFontSize(10);
  doc.setTextColor(r, g, b);
  doc.text("EVALUATION DETAILS", rightColX, metaY);
  metaY += 18;

  doc.setFont(primaryFont, normalStyle);
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);

  if (data.instructorName) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Instructor:", rightColX, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.instructorName, rightColX + 70, metaY);
    metaY += 15;
  }

  if (data.submissionDate) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Submitted:", rightColX, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.text(data.submissionDate, rightColX + 70, metaY);
    metaY += 15;
  }

  if (typeId === "internship-report" && data.companyName) {
    doc.setFont(primaryFont, boldStyle);
    doc.text("Company:", rightColX, metaY);
    doc.setFont(primaryFont, normalStyle);
    doc.setFontSize(8.5);
    const cmpName = data.companyName.split("\n")[0];
    doc.text(cmpName, rightColX + 70, metaY);
    doc.setFontSize(10);
  }

  // Stamp details
  doc.setDrawColor(r, g, b);
  doc.setLineWidth(1.2);
  doc.rect(pageWidth - margin - 100, currentY + 35, 75, 45);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("GRADE / MARKS", pageWidth - margin - 62, currentY + 46, { align: "center" });
  doc.text("SIGNATURE", pageWidth - margin - 62, currentY + 74, { align: "center" });

  // --- SECOND PAGE REDIRECT FOR RESEARCH DATA ---
  const hasSecondPage = typeId === "lab-report" || typeId === "homework" || typeId === "seminar-report";
  if (hasSecondPage) {
    doc.addPage();
    currentY = margin + 25;
    drawBordersAndGuides(2);

    if (typeId === "lab-report") {
      doc.setFont(primaryFont, boldStyle);
      doc.setFontSize(15);
      doc.setTextColor(r, g, b);
      doc.text("LABORATORY METHODOLOGY & OBSERVED DATA", margin, currentY);
      currentY += 18;
      
      drawLine(margin, currentY, pageWidth - margin, currentY, 1.5, [r, g, b]);
      currentY += 20;

      // Header stats Block
      doc.setFillColor(245, 245, 245);
      doc.rect(margin, currentY, pageWidth - 2 * margin, 40, "F");
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      
      doc.setFont(primaryFont, boldStyle);
      doc.text("Experiment:", margin + 15, currentY + 16);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.experimentNumber || "Experiment #1", margin + 85, currentY + 16);
      
      doc.setFont(primaryFont, boldStyle);
      doc.text("Performed:", margin + 15, currentY + 28);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.datePerformed || "N/A", margin + 85, currentY + 28);
      
      doc.setFont(primaryFont, boldStyle);
      doc.text("Partners:", pageWidth / 2 + 10, currentY + 16);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.groupMembers || "Individual", pageWidth / 2 + 70, currentY + 16);
      
      doc.setFont(primaryFont, boldStyle);
      doc.text("Course:", pageWidth / 2 + 10, currentY + 28);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.courseCode || "N/A", pageWidth / 2 + 70, currentY + 28);

      currentY += 60;

      const printPara = (secHeader: string, secBody: string) => {
        if (currentY > pageHeight - margin - 60) {
          doc.addPage();
          currentY = margin + 25;
          drawBordersAndGuides(doc.internal.pages.length - 1);
        }
        doc.setFont(primaryFont, boldStyle);
        doc.setFontSize(12);
        doc.setTextColor(r, g, b);
        doc.text(secHeader.toUpperCase(), margin, currentY);
        currentY += 15;
        drawLine(margin, currentY, margin + 40, currentY, 1, [r, g, b]);
        currentY += 15;

        // Paragraph line breaks
        doc.setFont(primaryFont, normalStyle);
        doc.setFontSize(10);
        doc.setTextColor(50, 50, 50);
        const splitText = doc.splitTextToSize(secBody || "No input.", pageWidth - 2 * margin);
        splitText.forEach((ln: string) => {
          if (currentY > pageHeight - margin - 30) {
            doc.addPage();
            currentY = margin + 25;
            drawBordersAndGuides(doc.internal.pages.length - 1);
            doc.setFont(primaryFont, normalStyle);
            doc.setFontSize(10);
            doc.setTextColor(50, 50, 50);
          }
          doc.text(ln, margin, currentY);
          currentY += 14;
        });
        currentY += 25;
      };

      if (data.objective) printPara("1. Objective", data.objective);
      if (data.materials) printPara("2. Materials & Apparatus", data.materials);
      if (data.procedure) printPara("3. Step-By-Step Procedure", data.procedure);
      if (data.results) printPara("4. Experimental Results", data.results);
      if (data.conclusion) printPara("5. Conclusion & Discussion", data.conclusion);
    } 
    
    else if (typeId === "homework") {
      doc.setFont(primaryFont, boldStyle);
      doc.setFontSize(15);
      doc.setTextColor(r, g, b);
      doc.text(data.homeworkNumber || "HOMEWORK SUBMISSION", margin, currentY);
      currentY += 18;
      drawLine(margin, currentY, pageWidth - margin, currentY, 1.5, [r, g, b]);
      currentY += 25;

      if (data.problemsAndSolutions) {
        const lines = data.problemsAndSolutions.split("\n");
        lines.forEach((line) => {
          const isProblem = line.trim().toLowerCase().startsWith("problem");
          const isSolution = line.trim().toLowerCase().startsWith("solution");

          if (currentY > pageHeight - margin - 35) {
            doc.addPage();
            currentY = margin + 25;
            drawBordersAndGuides(doc.internal.pages.length - 1);
          }

          if (isProblem) {
            currentY += 10;
            doc.setFont(primaryFont, boldStyle);
            doc.setTextColor(r, g, b);
            doc.setFontSize(11);
          } else if (isSolution) {
            currentY += 5;
            doc.setFont(primaryFont, boldStyle);
            doc.setTextColor(40, 40, 40);
            doc.setFontSize(10.5);
          } else {
            doc.setFont(primaryFont, normalStyle);
            doc.setTextColor(70, 70, 70);
            doc.setFontSize(10);
          }

          const splitline = doc.splitTextToSize(line, pageWidth - 2 * margin - (isSolution ? 10 : 0));
          splitline.forEach((subL: string) => {
            if (currentY > pageHeight - margin - 25) {
              doc.addPage();
              currentY = margin + 25;
              drawBordersAndGuides(doc.internal.pages.length - 1);
              doc.setFont(primaryFont, isProblem ? boldStyle : normalStyle);
              doc.setFontSize(9.5);
            }
            doc.text(subL, margin + (isSolution ? 10 : 0), currentY);
            currentY += 14;
          });
        });
      }
    } 
    
    else if (typeId === "seminar-report") {
      doc.setFont(primaryFont, boldStyle);
      doc.setFontSize(15);
      doc.setTextColor(r, g, b);
      doc.text("SEMINAR LOG ENTRY ABSTRACTS", margin, currentY);
      currentY += 18;
      
      drawLine(margin, currentY, pageWidth - margin, currentY, 1.5, [r, g, b]);
      currentY += 22;

      // Table description
      doc.setFillColor(248, 249, 250);
      doc.rect(margin, currentY, pageWidth - 2 * margin, 55, "F");
      doc.setDrawColor(220, 224, 230);
      doc.rect(margin, currentY, pageWidth - 2 * margin, 55);

      doc.setFontSize(9);
      doc.setFont(primaryFont, boldStyle);
      doc.setTextColor(40, 40, 40);
      doc.text("Speaker / Scholar Name:", margin + 15, currentY + 18);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.seminarSpeaker || "Unknown Guest", margin + 180, currentY + 18);

      doc.setFont(primaryFont, boldStyle);
      doc.text("Seminar Location / Venue:", margin + 15, currentY + 34);
      doc.setFont(primaryFont, normalStyle);
      doc.text(data.seminarVenue || "N/A", margin + 180, currentY + 34);

      doc.setFont(primaryFont, boldStyle);
      doc.text("Reported & Logged By:", margin + 15, currentY + 48);
      doc.setFont(primaryFont, normalStyle);
      doc.text(`${data.studentName || "N/A"} (${data.studentId || "N/A"})`, margin + 180, currentY + 48);

      currentY += 80;

      // Content abstracts
      doc.setFont(primaryFont, boldStyle);
      doc.setFontSize(12);
      doc.setTextColor(r, g, b);
      doc.text("REPORT ABSTRACT", margin, currentY);
      currentY += 15;
      drawLine(margin, currentY, margin + 60, currentY, 1, [r, g, b]);
      currentY += 20;

      doc.setFont(primaryFont, normalStyle);
      doc.setFontSize(10.5);
      doc.setTextColor(60, 60, 60);

      const splitAbs = doc.splitTextToSize(data.seminarAbstract || "No guest talk description added.", pageWidth - 2 * margin);
      splitAbs.forEach((line: string) => {
        if (currentY > pageHeight - margin - 30) {
          doc.addPage();
          currentY = margin + 25;
          drawBordersAndGuides(doc.internal.pages.length - 1);
          doc.setFont(primaryFont, normalStyle);
          doc.setFontSize(10.5);
        }
        doc.text(line, margin, currentY);
        currentY += 15;
      });
    }
  }

  // File save triggers
  const cleanStrName = (data.studentName || "academic").toLowerCase().replace(/\s+/g, "_");
  const filename = `${typeId}_doc_${cleanStrName}.pdf`;
  doc.save(filename);
}
